# docker compose -f docker-compose.prod.yml up -d

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - firefly-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgweb:
    image: sosedoff/pgweb
    ports:
      - "8081:8081"
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - PGWEB_SERVER_PORT=8081
      - PGWEB_SERVER_HOST=0.0.0.0
    command: ["--bind=0.0.0.0", "--listen=8081"]
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - firefly-net

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - firefly-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  firefly-server:
    image: firefly26710/firefly-insights-server:latest
    restart: always
    ports:
      - "21000:21000"
      - "32000:32000"
      - "33000:33000"
      - "34000:34000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RabbitMq__Host=rabbitmq
      - Serilog__SeqUrl=http://seq:5341
      - Jwt__Key=${JWT_KEY}
      
      - ConnectionStrings__UserDb=Host=postgres;Port=5432;Database=identitydb;Username=postgres;Password=postgres;
      - ConnectionStrings__ContentDb=Host=postgres;Port=5432;Database=contentsdb;Username=postgres;Password=postgres;
      - ConnectionStrings__AiDb=Host=postgres;Port=5432;Database=aidb;Username=postgres;Password=postgres;
      
      - Clusters__identityCluster__Address=http://127.0.0.1:32000
      - Clusters__contentsCluster__Address=http://127.0.0.1:33000
      - Clusters__aiCluster__Address=http://127.0.0.1:34000

      - Origin__ClientOrigins=${CLIENT_ORIGINS}

      - GmailOAuth__ClientId=${GOOGLE_CLIENT_ID}
      - GmailOAuth__ClientSecret=${GOOGLE_CLIENT_SECRET}
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - firefly-net

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=password123
    ports:
      - "5341:5341"
      - "8082:80"
    networks:
      - firefly-net

networks:
  firefly-net:
    driver: bridge

volumes:
  postgres-data: