// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Ai.Api.Infrastructure.Contexts;

#nullable disable

namespace Server.Ai.Api.Migrations
{
    [DbContext(typeof(AiContext))]
    partial class AiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("insights")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiChatConversation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("AiModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AiChatConversations", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AiChatConversationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AiModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AiChatConversationId");

                    b.ToTable("AiChatMessages", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AiProviderId")
                        .HasColumnType("bigint");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("InputPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("OutputPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AiProviderId");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("AiModels", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiProvider", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("AiProviders", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ArticleJob", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ArticleId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobLogId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobLogId")
                        .IsUnique();

                    b.ToTable("ArticleJobs", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExecutionPayloadId")
                        .HasColumnType("bigint");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<long>("JobLogId")
                        .HasColumnType("bigint");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPayloadId");

                    b.HasIndex("JobLogId")
                        .IsUnique();

                    b.ToTable("ExecutionLogs", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ExecutionPayload", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Response")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExecutionPayloads", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobFollowUp", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("JobLogId")
                        .HasColumnType("bigint");

                    b.Property<long>("ParentJobLogId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("JobLogId");

                    b.ToTable("JobFollowUps", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AiModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AiModelId");

                    b.ToTable("JobLogs", "insights");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiChatMessage", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.AiChatConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("AiChatConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiModel", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.AiProvider", "AiProvider")
                        .WithMany()
                        .HasForeignKey("AiProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiProvider");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ArticleJob", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.JobLog", "JobLog")
                        .WithOne()
                        .HasForeignKey("Server.Ai.Api.Models.Entities.ArticleJob", "JobLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobLog");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ExecutionLog", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.ExecutionPayload", "ExecutionPayload")
                        .WithMany()
                        .HasForeignKey("ExecutionPayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Ai.Api.Models.Entities.JobLog", "JobLog")
                        .WithOne("ExecutionLog")
                        .HasForeignKey("Server.Ai.Api.Models.Entities.ExecutionLog", "JobLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPayload");

                    b.Navigation("JobLog");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobFollowUp", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.JobLog", "JobLog")
                        .WithMany("FollowUps")
                        .HasForeignKey("JobLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobLog");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobLog", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.AiModel", "AiModel")
                        .WithMany()
                        .HasForeignKey("AiModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AiModel");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobLog", b =>
                {
                    b.Navigation("ExecutionLog");

                    b.Navigation("FollowUps");
                });
#pragma warning restore 612, 618
        }
    }
}
