// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Ai.Api.Infrastructure.Contexts;

#nullable disable

namespace Server.Ai.Api.Infrastructure.Contexts.Migrations
{
    [DbContext(typeof(AiContext))]
    [Migration("20260101132337_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("ai")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiChatConversation", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("AiModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("AiChatConversations", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiChatMessage", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AiChatConversationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("AiModelId")
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("AiChatConversationId");

                    b.ToTable("AiChatMessages", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("InputPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("OutputPrice")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("AiModels", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 10)
                        .HasColumnType("numeric(18,10)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExecutionPayloadId")
                        .HasColumnType("bigint");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<long>("JobLogId")
                        .HasColumnType("bigint");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionPayloadId");

                    b.HasIndex("JobLogId")
                        .IsUnique();

                    b.ToTable("ExecutionLogs", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ExecutionPayload", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ExecutionPayloads", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobFollowUp", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<long>("JobLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobLogId")
                        .IsUnique();

                    b.ToTable("JobFollowUps", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("AiModelId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AiModelId");

                    b.ToTable("JobLogs", "ai");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.AiChatMessage", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.AiChatConversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("AiChatConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.ExecutionLog", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.ExecutionPayload", "ExecutionPayload")
                        .WithMany()
                        .HasForeignKey("ExecutionPayloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Ai.Api.Models.Entities.JobLog", "JobLog")
                        .WithOne("ExecutionLog")
                        .HasForeignKey("Server.Ai.Api.Models.Entities.ExecutionLog", "JobLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionPayload");

                    b.Navigation("JobLog");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobFollowUp", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.JobLog", "JobLog")
                        .WithOne()
                        .HasForeignKey("Server.Ai.Api.Models.Entities.JobFollowUp", "JobLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobLog");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobLog", b =>
                {
                    b.HasOne("Server.Ai.Api.Models.Entities.AiModel", "AiModel")
                        .WithMany()
                        .HasForeignKey("AiModelId");

                    b.Navigation("AiModel");
                });

            modelBuilder.Entity("Server.Ai.Api.Models.Entities.JobLog", b =>
                {
                    b.Navigation("ExecutionLog");
                });
#pragma warning restore 612, 618
        }
    }
}
