name: Manual Test Deploy

on:
  workflow_dispatch:

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Remote Deploy
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: |
          ssh -o StrictHostKeyChecking=no cf-mac-server << EOF
            cd /Users/liqiangwang/Repo/Deploy/FireflyInsights

            curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -o docker-compose.prod.yml \
                 "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/docker-compose.prod.yml"
            
            export GOOGLE_CLIENT_ID="${GOOGLE_CLIENT_ID}"
            export GOOGLE_CLIENT_SECRET="${GOOGLE_CLIENT_SECRET}"

            export PATH=/usr/local/bin:/opt/homebrew/bin:\$PATH
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
          EOF